#!/bin/bash
fileid="1dCinFMc2O7oPLQnMS-GGcQWv-gyKYHQQ"
filename="model.pkl"
curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}" > /dev/null
curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=${fileid}" -o ${filename}